from datetime import datetime
from typing import Any
from pydantic import BaseModel, Field, model_validator
from backend.services.llm.base import ComplaintTriage


class ComplaintRecord(BaseModel):
    """Structured civic complaint record maintaining clean separation between:
    1. Raw citizen input
    2. Ground-truth benchmark data (for offline evaluation only)
    3. Operational lifecycle status
    4. Future AI prediction & operator decision slots
    """

    # --- 1. Raw Citizen Input ---
    complaint_id: str = Field(..., description="Unique complaint identifier, e.g. CMP-1001")
    source_channel: str = Field(..., description="Submission channel (e.g., CM Helpline, Mobile App)")
    timestamp: datetime = Field(..., description="Date and time when complaint was submitted")
    raw_text: str = Field(..., description="Verbatim raw citizen complaint text")

    # --- 2. Ground-Truth Data (Evaluation Benchmark Only; Hidden from AI during inference) ---
    language_ground_truth: str = Field(..., description="True language: English, Hindi, or Hinglish")
    department_ground_truth: str = Field(..., description="True municipal department from taxonomy")
    category_ground_truth: str = Field(..., description="True complaint category from taxonomy")
    locality_ground_truth: str | None = Field(default=None, description="True canonical locality if mentioned")
    ward_ground_truth: str | None = Field(default=None, description="True municipal ward number if known")
    urgency_ground_truth: str = Field(default="Medium", description="True ground-truth urgency level (Low, Medium, High, Critical)")
    incident_id: str = Field(..., description="Synthetic underlying incident ID (e.g. INC-001) for duplicate evaluation")

    # --- 3. Operational Status ---
    status: str = Field(..., description="Current status: 'Pending', 'In Progress', or 'Resolved'")
    resolved_at: datetime | None = Field(default=None, description="Resolution timestamp if resolved, else None")

    # --- 4. Extensibility: AI Prediction & Operator Review (Future Phases) ---
    ai_prediction: ComplaintTriage | None = Field(
        default=None,
        description="Structured prediction generated by LLM provider during inference (populated in future phases)"
    )
    operator_decision: dict[str, Any] | None = Field(
        default=None,
        description="Final human operator triage decisions/modifications (future phases)"
    )

    model_config = {"populate_by_name": True}

    @model_validator(mode="after")
    def validate_resolution_consistency(self) -> "ComplaintRecord":
        if self.status == "Resolved":
            if self.resolved_at is None:
                raise ValueError("Complaints with status 'Resolved' must have a non-null 'resolved_at' timestamp.")
            if self.resolved_at < self.timestamp:
                raise ValueError(
                    f"'resolved_at' ({self.resolved_at}) cannot be earlier than submission 'timestamp' ({self.timestamp})."
                )
        elif self.status == "Pending":
            if self.resolved_at is not None:
                raise ValueError("Complaints with status 'Pending' must have 'resolved_at' set to None.")
        return self
